#!/usr/bin/env node
/**
 * Generates src/data/pokemonNames.ts with the (lowercase, canonical) English
 * name of every Pokémon of the National Dex (1–1025), keyed by its Pokédex id.
 *
 * This lets the TierList search the entire dex instantly, without having to
 * paginate through the already-loaded Pokémon.
 *
 * Usage: node scripts/generate-names.mjs
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const LIST_URL = "https://pokeapi.co/api/v2/pokemon?limit=1025";

const SPOT_CHECKS = {
  1: "bulbasaur",
  6: "charizard",
  25: "pikachu",
  143: "snorlax",
  150: "mewtwo",
  242: "blissey",
  1025: "pecharunt",
};

const response = await fetch(LIST_URL);

if (!response.ok) {
  throw new Error(`Request failed: ${response.status} ${response.statusText}`);
}

const data = await response.json();

const records = (data.results || [])
  .map((entry) => ({
    id: Number(entry.url.split("/").filter(Boolean).pop()),
    name: entry.name,
  }))
  .filter((entry) => entry.id >= 1 && entry.id <= 1025)
  .sort((a, b) => a.id - b.id);

if (records.length !== 1025 || records[0].id !== 1 || records[1024].id !== 1025) {
  console.error(`ERROR: expected 1025 sequential Pokémon, got ${records.length}.`);
  process.exit(1);
}

for (const [id, expected] of Object.entries(SPOT_CHECKS)) {
  const actual = records[Number(id) - 1].name;

  if (actual !== expected) {
    console.error(`ERROR: #${id} is "${actual}", expected "${expected}".`);
    process.exit(1);
  }
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, "../src/data/pokemonNames.ts");

mkdirSync(dirname(outputPath), { recursive: true });

const rows = records
  .map((entry) => `  ${entry.id}: "${entry.name}",`)
  .join("\n");

const source = `/**
 * AUTO-GENERATED by scripts/generate-names.mjs — do not edit by hand.
 * Regenerate with: node scripts/generate-names.mjs
 * Source: https://pokeapi.co/api/v2/pokemon (National Dex 1–1025)
 */
export const POKEMON_NAMES: Record<number, string> = {
${rows}
};
`;

writeFileSync(outputPath, source, "utf8");

console.log(`Done! Wrote ${records.length} names to ${outputPath}`);