#!/usr/bin/env node
/**
 * Generates src/data/pokemonStats.ts with the base stats of every Pokémon of the
 * National Dex (1–1025) embedded in the bundle, plus a per-stat ranking.
 *
 * This lets the "Mejores stats" filter page by ranking instead of by Pokédex
 * number, so the best Pokémon of each stat are always visible from the start.
 *
 * Usage: node scripts/generate-stats.mjs
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const TOTAL_POKEMON = 1025;
const CONCURRENCY = 25;
const MAX_RETRIES = 3;
const BASE = "https://pokeapi.co/api/v2/pokemon";

const STAT_KEYS = [
  ["hp", "hp"],
  ["attack", "attack"],
  ["defense", "defense"],
  ["special-attack", "specialAttack"],
  ["special-defense", "specialDefense"],
  ["speed", "speed"],
];

const SORT_STATS = [
  "hp",
  "attack",
  "defense",
  "specialAttack",
  "specialDefense",
  "speed",
  "total",
];

function delay(ms) {
  return new Promise((fulfill) => setTimeout(fulfill, ms));
}

async function fetchWithRetry(url, retries = MAX_RETRIES) {
  try {
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`${response.status} ${response.statusText}`);
    }

    return await response.json();
  } catch (error) {
    if (retries <= 0) {
      throw error;
    }

    await delay(300);
    return fetchWithRetry(url, retries - 1);
  }
}

async function fetchStats(id) {
  const data = await fetchWithRetry(`${BASE}/${id}`);
  const byName = Object.fromEntries(
    data.stats.map((stat) => [stat.stat.name, stat.base_stat])
  );

  const stats = {};

  for (const [apiKey, field] of STAT_KEYS) {
    stats[field] = byName[apiKey] ?? 0;
  }

  return { id, stats };
}

async function runPool(ids) {
  const results = [];
  let cursor = 0;

  async function worker() {
    while (cursor < ids.length) {
      const id = ids[cursor];
      cursor += 1;

      try {
        results.push(await fetchStats(id));
      } catch (error) {
        console.error(`Failed to fetch stats for #${id}:`, error.message);
      }
    }
  }

  await Promise.all(Array.from({ length: CONCURRENCY }, () => worker()));
  return results;
}

function totalOf(stats) {
  return STAT_KEYS.reduce((sum, [, field]) => sum + stats[field], 0);
}

function formatChunks(values, chunkSize) {
  const lines = [];

  for (let i = 0; i < values.length; i += chunkSize) {
    const chunk = values.slice(i, i + chunkSize);
    lines.push(`    ${chunk.join(", ")},`);
  }

  return lines.join("\n");
}

function renderStats(records) {
  return records.map(({ id, stats }) => `  ${id}: { hp: ${stats.hp}, attack: ${stats.attack}, defense: ${stats.defense}, specialAttack: ${stats.specialAttack}, specialDefense: ${stats.specialDefense}, speed: ${stats.speed} },`).join("\n");
}

function renderRankings(records) {
  return SORT_STATS.map((stat) => {
    const ranked = [...records].sort((a, b) => {
      const difference = b.values[stat] - a.values[stat];

      if (difference !== 0) {
        return difference;
      }

      return a.id - b.id;
    });

    return `  ${stat}: [\n${formatChunks(ranked.map((entry) => entry.id), 25)}\n  ],`;
  }).join("\n");
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, "../src/data/pokemonStats.ts");

console.log("Fetching stats for Pokémon 1–" + TOTAL_POKEMON + "…");

const ids = Array.from({ length: TOTAL_POKEMON }, (_, index) => index + 1);
const fetched = await runPool(ids);
const records = fetched
  .map((entry) => ({ ...entry, values: { ...entry.stats, total: totalOf(entry.stats) } }))
  .sort((a, b) => a.id - b.id);

if (records.length !== TOTAL_POKEMON) {
  const missing = Array.from(
    { length: TOTAL_POKEMON },
    (_, index) => index + 1
  ).filter((id) => !records.some((entry) => entry.id === id));
  console.error(`\nERROR: expected ${TOTAL_POKEMON} Pokémon, got ${records.length}.`);
  console.error(`Missing IDs: ${missing.join(", ")}`);
  process.exit(1);
}

mkdirSync(dirname(outputPath), { recursive: true });

const source = `/**
 * AUTO-GENERATED by scripts/generate-stats.mjs — do not edit by hand.
 * Regenerate with: node scripts/generate-stats.mjs
 * Source: https://pokeapi.co/api/v2/pokemon (base stats, National Dex 1–${TOTAL_POKEMON})
 */
import type { PokemonStats, PokemonSortStat } from "../types/pokemon";

export const ALL_POKEMON_STATS: Record<number, PokemonStats> = {
${renderStats(records)}
};

export const POKEMON_STAT_RANKINGS: Record<PokemonSortStat, number[]> = {
${renderRankings(records)}
};
`;

writeFileSync(outputPath, source, "utf8");

console.log(`Done! Wrote ${records.length} Pokémon to ${outputPath}`);